name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # 当推送以 v 开头的标签时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Update version numbers
      run: |
        # 从 tag 中提取版本号（去掉 v 前缀）
        VERSION=${GITHUB_REF#refs/tags/v}
        # 更新 setup.py 中的版本号
        sed -i "s/<PYPI_VERSION>/$VERSION/" setup.py
        # 更新 __init__.py 中的版本号
        sed -i "s/<PYPI_VERSION>/$VERSION/" cloud189/__init__.py
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/* 